---
- name: Create VM vshphere
  hosts: localhost
  connection: local 
  tasks:
    - vmware_guest:
       hostname: vmlabvct001.labvmware.local
       username: Administrator@vsphere.local
       password: P@ssword1234
       validate_certs: no
       datacenter: 'Datacenter¨Paris'
       folder: /PROD/
       guest_id: centos64Guest
       name: test_vm_0001
       state: present
       disk:
       - size_gb: 10
         type: thin
         datastore: FreeNAS1
       hardware:
         memory_mb: 512
         num_cpus: 4
         scsi: paravirtual
      register: deploy_vm
